In [18]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import utils.plots as plots
import utils.data_wrangling as dw
import utils.data_integrity as di

In [2]:
os.getcwd()

'c:\\Users\\user\\Projetos\\load_forecasting\\src'

# Dados do ONS

In [24]:
data = dw.ons_data(ano_inicio=2012, ano_fim=2023, freq='h', idreg='S')
data.read()
df_load = data.data.loc['2012':'2023',:]
df_load.head()

                    id_reg desc_reg  load_mwmed
date
2012-01-01 00:00:00      S      SUL    7253.940
2012-01-01 01:00:00      S      SUL    6890.371
2012-01-01 02:00:00      S      SUL    6414.702
2012-01-01 03:00:00      S      SUL    6093.842
2012-01-01 04:00:00      S      SUL    5908.571

In [43]:
md = di.check_date_range(df_load, date_col_name="date", frequency="h", date_is_index=True)[1]
md

[Timestamp('2012-10-21 00:00:00'), Timestamp('2013-10-20 00:00:00')]

In [45]:
df_load.shape

(97846, 3)

In [44]:
df_load2 = di.input_missing_dates(df_load, date_col_name="date", missing_dates_=md, date_is_index=True)
df_load2.set_index("date", inplace=True)
di.check_date_range(df_load2, date_col_name="date", frequency="h", date_is_index=True)

'Sem datas faltantes.'

In [46]:
df_load2.shape

(97848, 3)

# Dados de temperatura

In [7]:
temp_data = dw.inmet_data(2012,2023)

In [8]:
temp_data.read_parquet()

In [ ]:
df_temp = temp_data.data
for col in df_temp.columns:
    plots.plot_ts(y_=df_temp[col], x_=df_temp.index, title_=f"{col} (original)", save=True)
    # plt.figure(figsize=(15,5))
    # plt.plot(df[col])
    # plt.title(col)
    # plt.show()

In [21]:
df_temp.head()

,precipitacao_total_horario_mm,pressao_atmosferica_ao_nivel_da_estacao_horaria_m_b,pressao_atmosferica_max_na_hora_ant_aut_m_b,pressao_atmosferica_min_na_hora_ant_aut_m_b,radiacao_global_kj_m,temperatura_do_ar_bulbo_seco_horaria_c,temperatura_do_ponto_de_orvalho_c,temperatura_maxima_na_hora_ant_aut_c,temperatura_minima_na_hora_ant_aut_c,temperatura_orvalho_max_na_hora_ant_aut_c,temperatura_orvalho_min_na_hora_ant_aut_c,umidade_rel_max_na_hora_ant_aut_%,umidade_rel_min_na_hora_ant_aut_%,umidade_relativa_do_ar_horaria_%,vento_direcao_horaria_gr_gr,vento_rajada_maxima_m_s,vento_velocidade_horaria_m_s
data_hora,,,,,,,,,,,,,,,,,
2012-01-01 00:00:00,36.300979,954.443832,954.536817,953.927791,1347.938460,19.206785,16.522620,19.882959,19.047813,16.882884,16.244390,86.401429,82.291657,85.332819,126.349376,6.453943,2.892819
2012-01-01 01:00:00,26.500979,954.756652,954.841945,954.349586,1330.269443,18.947810,16.325184,19.430395,18.758069,16.730320,16.111057,87.234763,83.573708,85.691793,147.708351,6.210353,2.803076
2012-01-01 02:00:00,21.700979,954.732293,954.965022,954.576509,1314.441572,18.656785,16.282877,19.106036,18.482428,16.559807,16.023877,87.811686,84.701914,86.845639,139.964761,5.869327,2.627435
2012-01-01 03:00:00,14.900979,954.400242,954.812458,954.350868,1285.867876,18.420887,16.229030,18.849626,18.251659,16.485448,16.005929,88.465532,85.701914,87.653332,141.041684,5.785994,2.690255
2012-01-01 04:00:00,16.500979,953.898960,954.444509,953.868817,1270.215482,18.163195,16.191851,18.598344,17.993967,16.477756,15.970031,89.606558,86.842939,88.704614,145.054505,5.728302,2.573588

In [31]:
di.check_date_range(data=df_load, date_col_name="date", frequency="h", date_is_index=True)

('Datas faltantes: ',
 [Timestamp('2012-10-21 00:00:00'), Timestamp('2013-10-20 00:00:00')])

# Comparando dados

In [40]:
df_load2

                    id_reg desc_reg  load_mwmed
date
2012-01-01 00:00:00      S      SUL    7253.940
2012-01-01 01:00:00      S      SUL    6890.371
2012-01-01 02:00:00      S      SUL    6414.702
2012-01-01 03:00:00      S      SUL    6093.842
2012-01-01 04:00:00      S      SUL    5908.571
...                    ...      ...         ...
2023-02-28 19:00:00      S      SUL   15729.786
2023-02-28 20:00:00      S      SUL   15462.558
2023-02-28 21:00:00      S      SUL   15239.737
2023-02-28 22:00:00      S      SUL   14644.277
2023-02-28 23:00:00      S      SUL   13548.623

[97848 rows x 3 columns]

In [48]:
df_load2 = df_load2.loc["2012-01-01":"2023-02-28"]
df_load2.shape

(97848, 3)

In [49]:
df_temp.shape

(97848, 17)

In [28]:
df_load.shape

(97846, 3)

In [29]:
df_temp.shape

(97848, 17)

In [69]:
def merge_dataframes(data1: pd.DataFrame, data2: pd.DataFrame, date1: str, date2: str, dt_min, dt_max, freq_='h', reset_index=False) -> pd.DataFrame:
    dt_range = pd.date_range(dt_min, dt_max, freq=freq_).to_series(name="datetime")
    df1 = pd.merge(dt_range, data1, left_on = "datetime", right_on=date1, how='outer')
    df2 = pd.merge(df1, data2, left_on=date1, right_on=date2, how='outer')
    return df2

In [68]:
merge_dataframes(data1=df_load.reset_index(), data2=df_temp.reset_index(), date1="date", date2="data_hora", dt_min=df_load.index.min(), dt_max=df_load.index.max())

,datetime,date,id_reg,desc_reg,load_mwmed,data_hora,precipitacao_total_horario_mm,pressao_atmosferica_ao_nivel_da_estacao_horaria_m_b,pressao_atmosferica_max_na_hora_ant_aut_m_b,pressao_atmosferica_min_na_hora_ant_aut_m_b,...,temperatura_maxima_na_hora_ant_aut_c,temperatura_minima_na_hora_ant_aut_c,temperatura_orvalho_max_na_hora_ant_aut_c,temperatura_orvalho_min_na_hora_ant_aut_c,umidade_rel_max_na_hora_ant_aut_%,umidade_rel_min_na_hora_ant_aut_%,umidade_relativa_do_ar_horaria_%,vento_direcao_horaria_gr_gr,vento_rajada_maxima_m_s,vento_velocidade_horaria_m_s
0,2012-01-01 00:00:00,2012-01-01 00:00:00,S,SUL,7253.940,2012-01-01 00:00:00,36.300979,954.443832,954.536817,953.927791,...,19.882959,19.047813,16.882884,16.244390,86.401429,82.291657,85.332819,126.349376,6.453943,2.892819
1,2012-01-01 01:00:00,2012-01-01 01:00:00,S,SUL,6890.371,2012-01-01 01:00:00,26.500979,954.756652,954.841945,954.349586,...,19.430395,18.758069,16.730320,16.111057,87.234763,83.573708,85.691793,147.708351,6.210353,2.803076
2,2012-01-01 02:00:00,2012-01-01 02:00:00,S,SUL,6414.702,2012-01-01 02:00:00,21.700979,954.732293,954.965022,954.576509,...,19.106036,18.482428,16.559807,16.023877,87.811686,84.701914,86.845639,139.964761,5.869327,2.627435
3,2012-01-01 03:00:00,2012-01-01 03:00:00,S,SUL,6093.842,2012-01-01 03:00:00,14.900979,954.400242,954.812458,954.350868,...,18.849626,18.251659,16.485448,16.005929,88.465532,85.701914,87.653332,141.041684,5.785994,2.690255
4,2012-01-01 04:00:00,2012-01-01 04:00:00,S,SUL,5908.571,2012-01-01 04:00:00,16.500979,953.898960,954.444509,953.868817,...,18.598344,17.993967,16.477756,15.970031,89.606558,86.842939,88.704614,145.054505,5.728302,2.573588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97845,2023-02-28 21:00:00,2023-02-28 21:00:00,S,SUL,15239.737,2023-02-28 21:00:00,67.163123,959.950019,960.325456,959.764034,...,27.246955,25.389535,18.178547,16.459892,65.159375,56.476384,64.045197,129.495177,6.214091,2.680764
97846,2023-02-28 22:00:00,2023-02-28 22:00:00,S,SUL,14644.277,2023-02-28 22:00:00,44.764222,960.230724,960.363156,959.834481,...,25.600383,23.778998,18.150916,16.822082,71.297679,62.906265,70.183340,121.069401,5.753989,2.173024
97847,2023-02-28 23:00:00,2023-02-28 23:00:00,S,SUL,13548.623,2023-02-28 23:00:00,25.976615,960.687744,960.801088,960.141004,...,23.980965,22.655179,18.111817,17.043255,75.812164,68.836290,74.195396,114.857280,5.106194,2.146291
97848,NaT,NaT,NaN,NaN,NaN,2012-10-21 00:00:00,33.512065,956.692882,956.948147,956.306171,...,20.747122,19.811940,17.103068,16.509641,83.740559,78.608843,82.361300,154.502844,4.724531,1.933462
97849,NaT,NaT,NaN,NaN,NaN,2013-10-20 00:00:00,0.000000,956.150865,956.172596,955.729808,...,19.984712,18.805769,13.010777,12.018767,69.994311,63.601748,68.181571,120.556650,3.349856,1.615531

In [70]:
date = merge_dataframes(data1=df_load.reset_index(), data2=df_temp.reset_index(), date1="date", date2="data_hora", dt_min=df_load.index.min(), dt_max=df_load.index.max())

In [75]:
date["2012-10-21"]

2012-10-21 00:00:00   2012-10-21 00:00:00
2012-10-21 01:00:00   2012-10-21 01:00:00
2012-10-21 02:00:00   2012-10-21 02:00:00
2012-10-21 03:00:00   2012-10-21 03:00:00
2012-10-21 04:00:00   2012-10-21 04:00:00
2012-10-21 05:00:00   2012-10-21 05:00:00
2012-10-21 06:00:00   2012-10-21 06:00:00
2012-10-21 07:00:00   2012-10-21 07:00:00
2012-10-21 08:00:00   2012-10-21 08:00:00
2012-10-21 09:00:00   2012-10-21 09:00:00
2012-10-21 10:00:00   2012-10-21 10:00:00
2012-10-21 11:00:00   2012-10-21 11:00:00
2012-10-21 12:00:00   2012-10-21 12:00:00
2012-10-21 13:00:00   2012-10-21 13:00:00
2012-10-21 14:00:00   2012-10-21 14:00:00
2012-10-21 15:00:00   2012-10-21 15:00:00
2012-10-21 16:00:00   2012-10-21 16:00:00
2012-10-21 17:00:00   2012-10-21 17:00:00
2012-10-21 18:00:00   2012-10-21 18:00:00
2012-10-21 19:00:00   2012-10-21 19:00:00
2012-10-21 20:00:00   2012-10-21 20:00:00
2012-10-21 21:00:00   2012-10-21 21:00:00
2012-10-21 22:00:00   2012-10-21 22:00:00
2012-10-21 23:00:00   2012-10-21 23:00:00
Freq: H, Name: datetime, dtype: datetime64[ns]